"""empty message

Revision ID: 8a2b53110a08
Revises: 9f9ac5621d2a
Create Date: 2026-06-21 17:12:26.751485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a2b53110a08'
down_revision: Union[str, Sequence[str], None] = '9f9ac5621d2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_ai', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_column('messages', 'is_ai')
    # ### end Alembic commands ###
